title: Madhuri Singh
email: madhuri.states@gmail.com
domain: madhuri.github.io
# description: >


home_content: |
  <!-- Add a profile image. Use the site-root path for the image. -->
  Welcome to my page, I am currently pursuing a PhD in Computer Science, advised by Dr. Mark Riedl at the Georgia Institute of Technology. 
  
  ![Madhuri](/Madhuri_image.jpg){:alt="Madhuri"}
  (My general appearance)

  ---

  ## Research
  My research aims to make Machine Learning systems Explainable, with a focus on Explainabile Reinforcement Learning. I also spend some time creating Artificial Narrow Intelligence tools to help in educational settings.
  You can see some of my work here:

  ### Workshop
  * <a href="https://arxiv.org/abs/2505.08073">Explainable Reinforcement Learning Agents Using World Models </a>

  ### Papers
  * <a href="https://link.springer.com/article/10.1007/s00521-024-10951-3">Experiential Explanations for Reinforcement Learning</a>
  * <a href="https://dl.acm.org/doi/abs/10.1145/3657604.3664676">Transforming CS Education with DevOps: Streamlined Assignment Validation and Delivery @ Scale</a>


  ## Contact

  Email: <a href="mailto:madhuri.states@gmail.com">madhuri.states@gmail.com</a>

  ## Relevant Links

  - [LinkedIn](https://www.linkedin.com/in/madhuri-singh-778a8a213)
  - [Google Scholar](https://scholar.google.com/citations?user=eNeMEbQAAAAJ&hl=en)


baseurl: "" # the subpath of your site, e.g. /blog
url: https://madhurisingh.com 
# remote_theme: pages-themes/midnight@v0.2.0
theme: minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Store homepage content here. This will be rendered in index.markdown using
# `{{ site.home_content | markdownify }}`. NOTE: Liquid tags inside this
# string will not be evaluated, so paths and emails are literal.
