title: Madhuri Singh
email: madhuri.states@gmail.com
domain: madhuri.github.io
# description: >


url: https://madhurisingh.com 
remote_theme: pages-themes/midnight@v0.2.0
# theme: minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Previously the homepage content was stored in `home_content` here. It has
# been moved into `index.markdown` so Liquid tags and includes work correctly.
